# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HandprintGenerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItemComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ActionItemInactive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ActionItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('links', models.CharField(max_length=500)),
                ('images', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionItemTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandprintGenerator.ActionItems')),
            ],
        ),
        migrations.CreateModel(
            name='ActionItemVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandprintGenerator.ActionItems')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='actionitemtags',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandprintGenerator.User'),
        ),
        migrations.AddField(
            model_name='actionitems',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandprintGenerator.User'),
        ),
        migrations.AddField(
            model_name='actioniteminactive',
            name='action_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandprintGenerator.ActionItems'),
        ),
        migrations.AddField(
            model_name='actionitemcomments',
            name='action_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HandprintGenerator.ActionItems'),
        ),
    ]
