# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandprintGenerator', '0002_auto_20160329_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionidea',
            name='images',
        ),
        migrations.AddField(
            model_name='actionidea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
