# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HandprintGenerator', '0002_auto_20160302_2027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActionItems',
            new_name='ActionItem',
        ),
        migrations.RenameModel(
            old_name='ActionItemComments',
            new_name='ActionItemComment',
        ),
        migrations.RenameModel(
            old_name='ActionItemTags',
            new_name='ActionItemTag',
        ),
        migrations.RenameModel(
            old_name='ActionItemVotes',
            new_name='ActionItemVote',
        ),
    ]
