# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandprintGenerator', '0003_auto_20160303_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionitem',
            old_name='links',
            new_name='references',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
