# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandprintGenerator', '0003_auto_20160330_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionidea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
