# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 04:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HandprintGenerator', '0004_auto_20160313_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 15, 4, 3, 49, 868655, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionitemcomment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 15, 4, 4, 8, 587891, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actioniteminactive',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 15, 4, 4, 12, 26426, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 15, 4, 4, 21, 63341, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('mod', 'Moderator'), ('member', 'Member')], default='member', max_length=15),
        ),
    ]
