# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandprintGenerator', '0004_auto_20160331_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionideainactive',
            name='reason',
            field=models.CharField(choices=[('duplicate', 'Duplicate'), ('accident', 'Accident'), ('spam', 'Spam'), ('inappropriate', 'Inappropriate'), ('inaccurate', 'Inaccurate'), ('other', 'Other')], max_length=15),
        ),
    ]
