# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandprintGenerator', '0005_auto_20160315_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('commute', 'Commute'), ('other', 'Other')], default='home', max_length=15),
            preserve_default=False,
        ),
    ]
