# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HandprintGenerator', '0006_actionitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 16, 19, 8, 52, 353307, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
