# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 03:06
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('HandprintGenerator', '0006_auto_20160406_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionidea',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
