# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandprintGenerator', '0008_auto_20160316_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('community', 'Community'), ('food', 'Food'), ('mobility', 'Mobility'), ('clothing', 'Clothing'), ('other', 'Other')], max_length=15),
        ),
    ]
