# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandprintGenerator', '0009_auto_20160318_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
